### ISSUE TITLE
🐛 [Bug Report] - Tauren - War Stomp triggers the GCD

### ISSUE THREAD

**Issue by schanzee** [Yatzii93/TBC5MAN-Bug-Tracker#116]
# Decription: #
war stomp triggers the gcd
# How it works: #
war stomp triggers the gcd
# How it should work: #
shouldnt trigger gcd
# Source - You need to provide a source as evidence: #
https://de.wowhead.com/spell=20549/kriegsdonner#comments:id=148490
# Additional Information: #

**Comment by Yatzii93** [comment]
Linking the commnets from wowhead is not the correct way to provide a source for something you think is incorrect. For one, the spell would have changed over the 15+ years the games been around. Just because it acted different in one time period doesn't mean it acted the same during TBC. Additionally, user comments are not reliable at all they are frequenctly wrong. Closing for now considering this isn't a good bug report. Please feel free to provide further information to back your claim and I will be happy to reopen.

**Comment by schanzee** [comment]
https://wowwiki.fandom.com/wiki/War_Stomp?oldid=1446536
"Since the ability does not affect the global cooldown for a full 1.5 seconds, you can immediately cast a small heal after it if you are a Shaman or a Druid. "
