### ISSUE TITLE
🐛 [Bug Report] - [Black temple - Flame of Azzinoth (Illidan Stormrage fight)] Crushing blows

### ISSUE THREAD

**Issue by p0tatis** [Yatzii93/TBC5MAN-Bug-Tracker#127]
# Decription: 
Having problems with the Flame of Azzinoth add on the illidan fight doing crushing blows on my tank in BT.

# How it works: 
The Flame of Azzinoth is doing crushing blows. Ive checked my combat log and most hits are crushing, but not all. At first I thought I was missing out on using holy shield (paladin tank), but I wasnt. 

# How it should work: 
Should not be able to do crushing blows.

# Source - You need to provide a source as evidence: 
https://wowwiki.fandom.com/wiki/Illidan_Stormrage_(tactics)#Flames_of_Azzinoth

![wiki](https://user-images.githubusercontent.com/76652870/103172558-a190b480-4854-11eb-8971-18775044ab02.png)

# Additional Information: 

https://tbcdb.com/?npc=22997

Heres a screenshot showing my defense, my combined avoidance making me non crushable and the combat log showing the "holy shield" ability fading a while after the crushing blow, which is almost 4.8k. According to the wiki its about the damage of the original 25 man raid. It also a shows one melee attack which didnt crush for some reason.

![Flame](https://user-images.githubusercontent.com/76652870/103172284-b66c4880-4852-11eb-89be-bab71406d051.png)

**Comment by Yatzii93** [comment]
I'll have to check to see if it's just crushing regardless of a players defense rating. If so then Im reluctant to change it considering it will mess with the already set 5 man scale, rather just leave as is.

**Comment by Tankdiehutte** [comment]
https://wowwiki-archive.fandom.com/wiki/Illidan_Stormrage_(tactics)#Flames_of_Azzinoth
"Melee: ~15k fire damage base, average of ~4k/hit with 365 resistance. Cannot crush or be blocked, but can crit, miss and be dodged or parried "
Crushing can only be prevented by either dodging, parrying, blocking or the attack missing. 
Since elemental autohits ( Flame of azzinoth, hydross, Solarian ) cant be blocked the "Can not crush" needs to be programmed into the autohit. A Comparison would be: Hard Hitter bosses like Brutallus or Archimonde which also cant crush.
