### ISSUE TITLE
🐛 [Bug Report] - [Paladin] - Sanctity Aura

### ISSUE THREAD

**Issue by ziokisame** [Yatzii93/TBC5MAN-Bug-Tracker#131]
# Decription: #
Reading the tooltip: "Increases Holy damage done by 10% for all party members within 30 yards. Players may only have one Aura on them per Paladin at any one time."

# How it works: #
It increases the damage only from certain spells, like consecration, exorcism. The problem is that at the moment it is not increasing seals damage, which should of course be buffed from the aura.

# How it should work: #
It should increase ALL holy sources damage, seals included.

# Source - You need to provide a source as evidence: #
I tried to test this with all seals, but its is impossible to determine mathematically on seal of command and blood if its working or not because the margin of damage is variable. Anyway you can see that with those seals you get always the same min-max hit and crits, with aura active or not.

With seal of righteousness the bug is clear. The damage from this seal is fixed so it is certainly bugged.
![Schermata 2021-02-01 alle 13 11 27](https://user-images.githubusercontent.com/32264419/106457842-db765b80-648f-11eb-88b4-12119f08378e.png)
3 stacks of vengeance, Sanctity aura active, 179 damage on swing.

![Schermata 2021-02-01 alle 13 11 40](https://user-images.githubusercontent.com/32264419/106458215-5b9cc100-6490-11eb-8792-990532ac7886.png)
3 stacks of vengeance, Sanctity aura inactive, 179 damage on swing. 

From WOWIKI: Sanctity Aura is very useful for shockadins (40/0/21 build), because it increases their Holy Shock and Seal of Righteousness damage by 10%. https://wowwiki.fandom.com/wiki/Sanctity_Aura_(removed_retribution_talent)

From WOWPEDIA: https://wow.gamepedia.com/Sanctity_Aura#:~:text=Sanctity%20Aura%20is%20a%20passive,It%20increases%20Versatility%20by%203%25.&text=You%20radiate%20holy%20energy%2C%20granting,and%20raid%20members%203%25%20Versatility.

# Additional Information: #

I sticked for 30 mins to the dummy hitting with seal of command and switching on-off the aura: max hit was always 1100 with 3 vengeance and no extra buff procs. the difference of damage should be around 110 extra damage, pretty noticeable, the same goes for seal of blood, max hit was always  around 580. On crit is even more noticeable, command crit was always 2200, we should notice a difference around 220 extra dmg.

**Comment by Dodonik1** [comment]
Partial confirmation as of as of today. Sanc aura works for consecrate and seal of vengance. Does NOT work for SoR.  As a matter of fact SoR is not affected by one hand specialisation or improved seal of righeousness talent so i feel like the problem in the those melle seals and not with sancity aura...
![Evi 1](https://user-images.githubusercontent.com/81078202/111910330-3aecf280-8a61-11eb-8bf0-a7483efbe129.png)
![Evi 2](https://user-images.githubusercontent.com/81078202/111910331-3c1e1f80-8a61-11eb-89f8-ecba8d023b75.png)

![3](https://user-images.githubusercontent.com/81078202/111910410-8e5f4080-8a61-11eb-99e1-03cf5501f7a5.png)
![2](https://user-images.githubusercontent.com/81078202/111910417-93bc8b00-8a61-11eb-83c3-1da9a76ba2bb.png)

**Comment by Yatzii93** [comment]
I'll check this out in the near future.

**Comment by Yatzii93** [comment]
>  improved seal of righeousness

https://us.forums.blizzard.com/en/wow/t/improved-seal-of-righteousness-does-not-affect-judgement-of-righteousness/421683/5
I'll check myself but make sure you are taking into account the fact that these talents dont effect spell power scaling, it's the base damage. You need to test this fully naked.

**Comment by Dodonik1** [comment]
Thanks for reading and reacting in a timely manner. Love the server and the work you have done with raids - the progression and difficulty  is on point. Keep holding yourself to a higher standard then current blizzard. 

Even if i was in gear i should have noticed at least a 1 base damage difference. Think SoR might be one of the easiest things to test in wow! :D Since you asked for some naked space goats here is a fresh test :D
![Evi 6](https://user-images.githubusercontent.com/81078202/112046542-79aba700-8b4c-11eb-9ec0-ced6e989ccef.png)
![Evi 7](https://user-images.githubusercontent.com/81078202/112046552-7ca69780-8b4c-11eb-82cf-b8a56df4134f.png)


I do agree it should be only base damage on the improved seal of righteousness if we wanted to be classic-like but trust me even if you buffed it to 15% increase after spellpower that would still not make paladins equals of warriors (100% more damage on devastate and shield slam) or druids that reguarly go 1k+ on single target dps) in the super lategame content (CM or the new AQ). Do note that past seals and consecrate everything scales rly low (long cd-s, low coeficient). You will be hard pressed to find a 700 dps prot paladin single target boss kill and holding those 2.5k+ dps-ers requires too much concessions that other tanks don t make (warrs do 800 +dps with both defansive trinkets).

ps: Sancity aura should affect after spellpower and one hand specialization should also work in that manner (they don t with SoR). From my tests 5x vengance (15% buff to physical and holy damage) buffs SoR by 15% O.o.

**Comment by Yatzii93** [comment]
one hand specialization is clearly working, not sure why this talent is now being brought into the discussion. 
![image](https://user-images.githubusercontent.com/47720837/112129414-4ce4a780-8bbf-11eb-85bc-b0c7f1b068f9.png)
![image](https://user-images.githubusercontent.com/47720837/112129426-4fdf9800-8bbf-11eb-8555-de4ac0cc3713.png)

**Comment by Yatzii93** [comment]
The problem with Improved Seal of Righteousness is fixed. It really should have been in a seperate issue because it's just confusing me now, as you can see I closed this thread thinking I'd fixed the reported bug ^^

**Comment by schanzee** [comment]
after the fix the 10% holy damage bonus from the aura affects what i assume is all schools of magic (atleast shadow and nature)
