### ISSUE TITLE
🐛 [Bug Report] - Enchant Gloves - Superior Agility is not giving a extra item

### ISSUE THREAD

**Issue by skyy0** [Yatzii93/TBC5MAN-Bug-Tracker#50]
# Decription: Enchant Gloves - Superior Agility is not giving an extra item

# How it works: #Enchant is going directly onto the Item

# How it should work: #Extra Item in the inventory

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by Yatzii93** [comment]
Enchanting TBC enchants now creates an item(similar to wotlk scrolls) which can apply said enchant rather than the current system where only the enchanter can apply the enchant via a trade window. These items can also be sold on the AH. No more hunting down enchanters everytime u get a new piece of gear that needs an enchant. This only works for enchants on this vendor – https://wowwiki.fandom.com/wiki/Enchantments_Vendor (Footage of how it works – https://youtu.be/FA0RmdXboVs?t=201)

**Comment by Yatzii93** [comment]
There may be work done in the future to include these enchants with custom items.
