### ISSUE TITLE
🐛 [Priest] - (Priest) Talents stop working

### ISSUE THREAD

**Issue by schanzee** [Yatzii93/TBC5MAN-Bug-Tracker#54]
# Decription: #
i don't know how it happens but at least some priest talents stop working after playing for some time. so far i've noticed this with improved power word fortitude, spirit tap, misery and i think meditation aswell. might be more that you aren't as obvious.
# How it works: #
talents stop working. relog fixes it. zone change doesnt fix it.
# How it should work: #
talents always work until you respec
# Source - You need to provide a source as evidence: #
...
# Additional Information: #
might affect other classes aswell

**Comment by ziokisame** [comment]
I noticed this too, I didnt figure out how but seems like your talents are counted as buffs or something and sometimes get removed. It affects also improved healing, healing prayers, spiritual guidance, spiritual healing, empowered healing. Basically the "passive" talents, active talents like inner focus, spirit of redemption, circle of healing and lightwell are still working. I noticed this since i was ooming crazy in the eye.

**Comment by oldspices** [comment]
this is probably from when you cast mind control- I just made a ticket about that @Yatzii93

**Comment by ziokisame** [comment]
There are 2 tickets opened regarding the same issue, i'm posting my results here also:
Ok so these are the results of my testing. The red marked talents completely stop working, the green ones are still perfectly working after mind control.
Pain suppression loses its dispel resistance but keeps the reduction on dmg (maybe the dispel is fucked up with a sort of interaction with silent resolve talent which is removed after mind control?).
The blue marked ones I was not sure if they were still working or not, tested them but since I wasn't sure I decided to put a big question mark on them.
![priest talent after mind control](https://user-images.githubusercontent.com/32264419/90231149-ff2ee200-de1a-11ea-9569-1869e65a4ffb.jpg)
